version: '3'
services:
  app:
    image : docker-luma-health
    build: ./src
    command: nodemon index.js
    ports:
      - "3000:3000"
    volumes:
      - ./src:/src/app
      - /src/app/node_modules
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"